"""
Step 16: Calculate Payback Periods

Calculate payback periods for electrification scenarios based on:
- Capital costs from step15_build_capital_costs_lifetimes_incentives.py
- Annual cost savings from operational cost differences between baseline and scenario

Data Sources:
1. Capital Costs: data/loadprofiles/capital_costs/capital_costs_{scenario}_{housing_type}.csv
   - Generated by step15_build_capital_costs_lifetimes_incentives.py
   - Contains: net_cost by county, appliance, and incentive scenario

2. Annual Costs (Baseline): 
   - Total: {county_dir}/results/totals/RESULTS_total_annual_costs_{county}_{timestamp}.csv
   - Generated by step13_combine_total_annual_costs.py
   
3. Annual Costs (Scenario):
   - Same structure as baseline, but for the specified electrification scenario

Payback Period Calculation:
- Annual Savings = Baseline Annual Costs - Scenario Annual Costs
- Payback Period = Net Capital Costs / Annual Savings (in years)

Output:
- CSV file: data/results/{housing_type}/payback_periods_{scenario}.csv
  Contains payback period data by county and incentive scenario
"""

import os
import pandas as pd
from helpers.main_helpers import log, slugify_county_name, norcal_counties, socal_counties, central_counties, get_scenario_path
from helpers.maps_helpers import get_latest_csv_file
from helpers.utility_helpers import get_utility_for_county

COMPARISON_BASELINE = {
    "baseline_ev_car": "baseline_ice_car",
    "full_electric_ev": "baseline_ice_car",
    # everything else falls back to plain "baseline"
}

def load_capital_costs(base_input_dir: str, scenario: str, housing_type: str) -> pd.DataFrame:
    """
    Load capital costs data from step15 output.
    
    Args:
        base_input_dir: Base input directory 
        scenario: Electrification scenario name
        housing_type: Housing type
        
    Returns:
        DataFrame with capital costs by county and incentive scenario
    """
    capital_costs_dir = os.path.join(base_input_dir, "capital_costs")
    csv_filename = f"capital_costs_{scenario}_{housing_type.replace('-', '_')}.csv"
    csv_path = os.path.join(capital_costs_dir, csv_filename)
    
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Capital costs file not found: {csv_path}")
    
    df = pd.read_csv(csv_path)
    log(
        at="load_capital_costs",
        info="capital_costs_loaded",
        rows_count=len(df),
        csv_path=csv_path
    )
    return df

def load_annual_costs(base_input_dir: str, county: str, scenario: str, housing_type: str, with_solar: bool = False) -> float:
    """
    Load annual total costs for a county and scenario, following the same pattern as capital_costs_helper.py.
    
    Args:
        base_input_dir: Base input directory
        county: Full county name (e.g., 'Alameda County')
        scenario: Scenario name ('baseline' or electrification scenario)
        housing_type: Housing type
        with_solar: Whether to load from solarstorage directory
        
    Returns:
        Annual total cost for the scenario
    """
    county_slug = slugify_county_name(county)
    
    if with_solar:
        # Load from solarstorage results directory
        results_dir = os.path.join(base_input_dir, scenario, housing_type, county_slug, "results", "solarstorage")
        expected_scenario = f"{scenario}.solarstorage"
    else:
        # Load from totals results directory  
        results_dir = os.path.join(base_input_dir, scenario, housing_type, county_slug, "results", "totals")
        expected_scenario = scenario
    
    if not os.path.exists(results_dir):
        log(
            at="load_annual_costs",
            info="results_directory_not_found",
            directory=results_dir
        )
        return 0.0
    
    try:
        # Get latest total annual costs file
        file_path = get_latest_csv_file(results_dir, f"RESULTS_total_annual_costs_{county_slug}_")
        df = pd.read_csv(file_path, index_col="scenario")
        
        if expected_scenario in df.index:
            # Use first column (usually the primary rate plan like total.PG&E.E-TOU-D+PG&E.G-1)
            cost_value = df.loc[expected_scenario]
            if hasattr(cost_value, 'iloc'):
                return float(cost_value.iloc[0])
            else:
                return float(cost_value)
        else:
            log(
                at="load_annual_costs",
                info="scenario_not_found",
                expected_scenario=expected_scenario,
                file_path=file_path,
                available_scenarios=list(df.index)
            )
            return 0.0
            
    except Exception as e:
        log(
            at="load_annual_costs",
            info="annual_costs_load_failed",
            county=county,
            scenario=scenario,
            with_solar=with_solar,
            error=str(e)
        )
        return 0.0

def load_pv_net_adders(base_input_dir: str, scenario: str, housing_type: str) -> pd.DataFrame:
    """
    Reads capital_costs_summary_with_pv_{scenario}_{housing_type}.csv
    and returns (county_slug, pv_storage_net_full/half/none).
    If file missing, returns empty df (treated as zeros downstream).
    """
    capital_costs_dir = os.path.join(base_input_dir, "capital_costs")
    fname = f"capital_costs_summary_with_pv_{scenario}_{housing_type.replace('-', '_')}.csv"
    path = os.path.join(capital_costs_dir, fname)

    if not os.path.exists(path):
        log(at="load_pv_net_adders", info="pv_summary_not_found", csv_path=path)
        return pd.DataFrame(columns=[
            'county_slug',
            'pv_storage_net_full', 'pv_storage_net_half', 'pv_storage_net_none'
        ])

    df = pd.read_csv(path)
    # Keep only what we need; if columns are missing, fill zeros
    needed = ['county_slug',
              'pv_storage_net_full', 'pv_storage_net_half', 'pv_storage_net_none']
    for col in needed:
        if col not in df.columns:
            df[col] = 0.0
    log(at="load_pv_net_adders", info="pv_summary_loaded", rows_count=len(df), csv_path=path)
    
    return df[needed]

def pv_adder_for(county_slug: str, incentive_scenario: str, pv_net_df: pd.DataFrame) -> float:
    if pv_net_df.empty:
        return 0.0
    row = pv_net_df[pv_net_df['county_slug'] == county_slug]
    if row.empty:
        return 0.0
    key = str(incentive_scenario).lower()
    col_map = {
        'full_incentives': 'pv_storage_net_full',
        'half_incentives': 'pv_storage_net_half',
        'no_incentives': 'pv_storage_net_none',
    }
    col = col_map.get(key)
    return float(row.iloc[0][col]) if col in row.columns else 0.0

def vehicle_annual_adders_from_ledger(ledger_df: pd.DataFrame) -> pd.DataFrame:
    """
    Returns a DataFrame indexed by county_slug with two columns:
      ev_operating  – annual O&M for electric vehicle rows (vehicle_charging)
      ice_operating – annual O&M for ICE vehicle rows (vehicle_fuel)
    If a scenario doesn't contain one of the vehicles, that column will be 0 for all counties.
    """
    df = ledger_df.copy()

    # Guard for missing columns (older CSVs)
    for col in ["county_slug", "appliance_category", "appliance_type", "annual_operating_cost"]:
        if col not in df.columns:
            df[col] = 0.0 if col != "appliance_type" else ""

    # EV O&M lives in electric / vehicle_charging rows
    ev = (df[(df["appliance_category"] == "electric") & (df["appliance_type"] == "vehicle_charging")]
            .groupby("county_slug", as_index=False)["annual_operating_cost"].sum()
            .rename(columns={"annual_operating_cost": "ev_operating"}))

    # ICE O&M lives in gas / vehicle_fuel rows
    ice = (df[(df["appliance_category"] == "gas") & (df["appliance_type"] == "vehicle_fuel")]
             .groupby("county_slug", as_index=False)["annual_operating_cost"].sum()
             .rename(columns={"annual_operating_cost": "ice_operating"}))

    out = pd.DataFrame({"county_slug": pd.unique(df["county_slug"])})
    out = (out.merge(ev,  on="county_slug", how="left")
              .merge(ice, on="county_slug", how="left")
              .fillna({"ev_operating": 0.0, "ice_operating": 0.0}))
    return out.set_index("county_slug")

def calculate_annual_savings(base_input_dir: str, county: str, scenario: str, housing_type: str):
    """
    Calculate annual savings for a county and scenario.
    
    Args:
        base_input_dir: Base input directory
        county: County name
        scenario: Scenario name
        housing_type: Housing type
        
    Returns:
        Tuple of (baseline_cost, scenario_cost, solar_cost, savings_scenario_only, savings_with_solar)
    """
    # 1. Baseline costs (no electrification)
    baseline_annual_cost = load_annual_costs(base_input_dir, county, "baseline", housing_type, with_solar=False)
    
    # 2. Scenario costs (electrification only, no solar)
    scenario_annual_cost = load_annual_costs(base_input_dir, county, scenario, housing_type, with_solar=False)
    
    # 3. Scenario + solar costs (electrification + solar+storage)
    scenario_solar_annual_cost = load_annual_costs(base_input_dir, county, scenario, housing_type, with_solar=True)
    
    if baseline_annual_cost == 0:
        log(
            at="calculate_annual_savings",
            info="missing_baseline_cost_data",
            county=county
        )
        return baseline_annual_cost, scenario_annual_cost, scenario_solar_annual_cost, 0.0, 0.0
        
    if scenario_annual_cost == 0 or scenario_solar_annual_cost == 0:
        log(
            at="calculate_annual_savings",
            info="missing_scenario_cost_data",
            county=county
        )
        return baseline_annual_cost, scenario_annual_cost, scenario_solar_annual_cost, 0.0, 0.0
    
    # Calculate annual savings (baseline - scenario)
    savings_scenario_only = baseline_annual_cost - scenario_annual_cost
    savings_with_solar = baseline_annual_cost - scenario_solar_annual_cost
    
    # print(f"{county}:")
    # print(f"  Baseline Annual: ${baseline_annual_cost:.0f}")
    # print(f"  {scenario} only Annual: ${scenario_annual_cost:.0f} (savings: ${savings_scenario_only:.0f})")
    # print(f"  {scenario} + solar Annual: ${scenario_solar_annual_cost:.0f} (savings: ${savings_with_solar:.0f})")

    return baseline_annual_cost, scenario_annual_cost, scenario_solar_annual_cost, savings_scenario_only, savings_with_solar


def _sam_csv_path(base_input_dir: str, scenario: str, housing_type: str, county_slug: str) -> str | None:
    county_dir = os.path.join(base_input_dir, scenario, housing_type, county_slug)
    a = os.path.join(county_dir, f"solar_storage_dispatch_profiles_{county_slug}.csv")
    b = os.path.join(county_dir, f"solar_storage_dispatch_profiles_{scenario}_{county_slug}.csv")
    if os.path.exists(a):
        return a
    if os.path.exists(b):
        return b
    return None


def _effective_electricity_price_info(base_input_dir: str, scenario: str, housing_type: str, county_slug: str) -> dict:
    """Return a dict with effective price info: price, utility, tariff, annual_cost, annual_kwh."""
    out = {
        "effective_price_per_kwh": 0.0,
        "effective_price_utility": None,
        "effective_price_tariff": None,
        "effective_price_annual_cost": 0.0,
        "effective_price_annual_kwh": 0.0,
    }
    try:
        county_dir = os.path.join(base_input_dir, scenario, housing_type, county_slug)
        lfr_path = os.path.join(county_dir, f"loadprofiles_for_rates_{county_slug}.csv")
        if not os.path.exists(lfr_path):
            return out
        df_lfr = pd.read_csv(lfr_path, low_memory=False)
        if 'default.electricity.kwh' not in df_lfr.columns:
            return out
        annual_kwh = float(df_lfr['default.electricity.kwh'].sum())
        out["effective_price_annual_kwh"] = annual_kwh
        if annual_kwh <= 0:
            return out

        scen_path = get_scenario_path(base_input_dir, scenario, housing_type)
        elec_dir = os.path.join(scen_path, county_slug, 'results', 'electricity')
        res_path = get_latest_csv_file(elec_dir, f"RESULTS_electricity_annual_costs_{county_slug}")
        df = pd.read_csv(res_path, index_col='scenario')
        row = df.loc[scenario] if scenario in df.index else df.iloc[0]
        util = get_utility_for_county(county_slug)
        cols = [c for c in row.index if c.startswith(f"electricity.{util}.")] or [c for c in row.index if c.startswith("electricity.")]
        if not cols:
            return out
        # Choose min annual cost and record tariff name
        valid = [(c, row[c]) for c in cols if pd.notnull(row[c])]
        if not valid:
            return out
        tariff, annual_cost = min(valid, key=lambda kv: kv[1])
        out["effective_price_utility"] = util
        out["effective_price_tariff"] = tariff
        out["effective_price_annual_cost"] = float(annual_cost)
        out["effective_price_per_kwh"] = float(annual_cost) / annual_kwh if annual_kwh > 0 else 0.0
        return out
    except Exception:
        return out

def _effective_electricity_price(base_input_dir: str, scenario: str, housing_type: str, county_slug: str) -> float:
    return _effective_electricity_price_info(base_input_dir, scenario, housing_type, county_slug).get("effective_price_per_kwh", 0.0)


def _total_pv_generation_kwh(base_input_dir: str, scenario: str, housing_type: str, county_slug: str) -> float:
    path = _sam_csv_path(base_input_dir, scenario, housing_type, county_slug)
    if not path:
        return 0.0
    try:
        df = pd.read_csv(path)
        total = 0.0
        if 'System to Load' in df.columns:
            total += float(df['System to Load'].sum())
        if 'System to Battery' in df.columns:
            total += float(df['System to Battery'].sum())
        if 'System to Grid' in df.columns:
            total += float(df['System to Grid'].sum())
        return total
    except Exception:
        return 0.0


def _pv_capacity_factor(base_input_dir: str, scenario: str, housing_type: str, county_slug: str, solar_kw: float | None) -> float:
    if not solar_kw or solar_kw <= 0:
        return 0.0
    gen = _total_pv_generation_kwh(base_input_dir, scenario, housing_type, county_slug)
    return gen / (solar_kw * 8760.0) if solar_kw > 0 else 0.0


def _self_supply_ratio(base_input_dir: str, scenario: str, housing_type: str, county_slug: str) -> float:
    path = _sam_csv_path(base_input_dir, scenario, housing_type, county_slug)
    if not path:
        return 0.0
    try:
        df = pd.read_csv(path)
        if 'Grid to Load' in df.columns and 'Load Profile' in df.columns:
            grid = float(df['Grid to Load'].sum())
            load = float(df['Load Profile'].sum())
            return 1.0 - (grid / load) if load > 0 else 0.0
        return 0.0
    except Exception:
        return 0.0


def _peak_period_load_share(base_input_dir: str, scenario: str, housing_type: str, county_slug: str) -> float:
    path = _sam_csv_path(base_input_dir, scenario, housing_type, county_slug)
    if not path:
        return 0.0
    try:
        df = pd.read_csv(path, parse_dates=[0], index_col=0)
        if 'Load Profile' not in df.columns:
            return 0.0
        hours = df.index.hour
        mask = (hours >= 16) & (hours < 21)
        peak = float(df.loc[mask, 'Load Profile'].sum())
        total = float(df['Load Profile'].sum())
        return (peak / total) if total > 0 else 0.0
    except Exception:
        return 0.0


def _diagnostic_counties() -> set[str]:
    """Return set of county slugs to log diagnostics for.
    Override with PAYBACK_DIAGNOSTIC_COUNTIES env (comma-separated county names or slugs)."""
    env = os.getenv("PAYBACK_DIAGNOSTIC_COUNTIES")
    if env:
        items = [slugify_county_name(x.strip()) for x in env.split(",") if x.strip()]
        return set(items)
    # Default: Alameda and nearby Bay Area counties for comparison
    return {"alameda", "contra-costa", "santa-clara", "san-francisco", "san-mateo"}


def _should_log_diagnostic(county_slug: str) -> bool:
    return county_slug in _diagnostic_counties()


def _capital_summary_details(base_input_dir: str, scenario: str, housing_type: str, county_slug: str) -> dict:
    """Return step14 summary fields to explain net_outlay_no_pv differences."""
    out = {
        "total_capital_cost_electric": 0.0,
        "capital_cost_gas": 0.0,
        "incentives_full": 0.0,
        "net_outlay_full": 0.0,
        "net_outlay_half": 0.0,
        "net_outlay_none": 0.0,
        "pv_capex": 0.0,
        "storage_capex": 0.0,
        "pv_incentives_full": 0.0,
        "storage_incentives_full": 0.0,
        "pv_storage_net_full": 0.0,
        "net_outlay_full_with_pv": 0.0,
        "net_outlay_half_with_pv": 0.0,
        "net_outlay_none_with_pv": 0.0,
        "solar_kw": 0.0,
    }
    cap_dir = os.path.join(base_input_dir, "capital_costs")
    base = f"{scenario}_{housing_type.replace('-', '_')}"
    summary_path = os.path.join(cap_dir, f"capital_costs_summary_{base}.csv")
    with_pv_path = os.path.join(cap_dir, f"capital_costs_summary_with_pv_{base}.csv")
    try:
        if os.path.exists(summary_path):
            df = pd.read_csv(summary_path, low_memory=False)
            row = df[df['county_slug'] == county_slug]
            if not row.empty:
                out["total_capital_cost_electric"] = float(row.iloc[0].get('total_capital_cost_electric', 0.0))
                out["capital_cost_gas"] = float(row.iloc[0].get('capital_cost_gas', 0.0))
                out["incentives_full"] = float(row.iloc[0].get('incentives_full', 0.0))
                out["net_outlay_full"] = float(row.iloc[0].get('net_outlay_full', 0.0))
                out["net_outlay_half"] = float(row.iloc[0].get('net_outlay_half', 0.0)) if 'net_outlay_half' in row.columns else 0.0
                out["net_outlay_none"] = float(row.iloc[0].get('net_outlay_none', 0.0)) if 'net_outlay_none' in row.columns else 0.0
        if os.path.exists(with_pv_path):
            dfp = pd.read_csv(with_pv_path, low_memory=False)
            rowp = dfp[dfp['county_slug'] == county_slug]
            if not rowp.empty:
                out["pv_capex"] = float(rowp.iloc[0].get('pv_capex', 0.0))
                out["storage_capex"] = float(rowp.iloc[0].get('storage_capex', 0.0))
                out["pv_incentives_full"] = float(rowp.iloc[0].get('pv_incentives_full', 0.0))
                out["storage_incentives_full"] = float(rowp.iloc[0].get('storage_incentives_full', 0.0))
                out["pv_storage_net_full"] = float(rowp.iloc[0].get('pv_storage_net_full', 0.0))
                out["net_outlay_full_with_pv"] = float(rowp.iloc[0].get('net_outlay_full_with_pv', 0.0))
                out["net_outlay_half_with_pv"] = float(rowp.iloc[0].get('net_outlay_half_with_pv', 0.0)) if 'net_outlay_half_with_pv' in rowp.columns else 0.0
                out["net_outlay_none_with_pv"] = float(rowp.iloc[0].get('net_outlay_none_with_pv', 0.0)) if 'net_outlay_none_with_pv' in rowp.columns else 0.0
                out["solar_kw"] = float(rowp.iloc[0].get('solar_kw', 0.0))
    except Exception:
        pass
    return out
    
def calculate_net_capital_cost(capital_summary: pd.DataFrame, county: str) -> pd.DataFrame:
    return capital_summary[capital_summary['county'] == county]

def summarize_incremental_capex_against_baseline(
    scen_df: pd.DataFrame, base_df: pd.DataFrame
) -> pd.DataFrame:
    """
    Compare electric net costs from the scenario against gas base costs
    from the chosen baseline (e.g., baseline_ice_car for EV scenarios).
    """
    s = scen_df.copy()
    b = base_df.copy()
    s['incentive_scenario'] = s['incentive_scenario'].str.lower()
    b['incentive_scenario'] = b['incentive_scenario'].str.lower()

    # scenario electrics
    elec = (
        s[s['appliance_category'] == 'electric']
        .groupby(['county','incentive_scenario'], as_index=False)['net_cost']
        .sum()
        .rename(columns={'net_cost':'electric_net'})
    )

    # baseline gas
    gas = (
        b[b['appliance_category'] == 'gas']
        .groupby(['county','incentive_scenario'], as_index=False)['base_cost']
        .sum()
        .rename(columns={'base_cost':'gas_base'})
    )

    out = elec.merge(gas, on=['county','incentive_scenario'], how='left').fillna({'gas_base':0.0})
    out['net_capital_cost_no_pv'] = out['electric_net'] - out['gas_base']
    return out[['county','incentive_scenario','net_capital_cost_no_pv']]

def calculate_payback_periods(base_input_dir: str, scenario: str, housing_type: str, counties: list) -> pd.DataFrame:
    """
    Calculate payback periods for all counties and incentive scenarios.
    
    Args:
        base_input_dir: Base input directory
        scenario: Electrification scenario name  
        housing_type: Housing type
        counties: List of counties to process
        
    Returns:
        DataFrame with payback period data
    """
    try:
        scenario_df = load_capital_costs(base_input_dir, scenario, housing_type)

        if scenario_df.empty:
            log(
                at="calculate_payback_periods",
                info="no_capital_costs_found",
                scenario=scenario
            )
            return pd.DataFrame()

        baseline_name = COMPARISON_BASELINE.get(scenario, "baseline")
        baseline_df  = load_capital_costs(base_input_dir, baseline_name, housing_type)

        scenario_vehicle_adders = vehicle_annual_adders_from_ledger(scenario_df)
        baseline_vehicle_adders = vehicle_annual_adders_from_ledger(baseline_df)

        print("scenario_vehicle_adders", scenario_vehicle_adders)
        print("baseline_vehicle_adders", baseline_vehicle_adders)
        
        # Legacy recompute (kept for debugging only); Option A fix will not rely on this
        capital_summary = summarize_incremental_capex_against_baseline(scenario_df, baseline_df)
        print("capital_summary (legacy, not used for numerators)", capital_summary)

        pv_net_df = load_pv_net_adders(base_input_dir, scenario, housing_type)
        print("pv_net_df", pv_net_df)

        log(
            at="calculate_payback_periods",
            info="capital_costs_summary_created",
            combinations_count=len(capital_summary)
        )
        
        payback_data = []
        
        for county in counties:
            try:
                # Calculate annual costs and savings
                baseline_annual_cost, scenario_annual_cost, scenario_solar_annual_cost, savings_scenario_only, savings_with_solar = calculate_annual_savings(
                    base_input_dir, county, scenario, housing_type
                )

                county_slug = slugify_county_name(county)
                print("county_slug", county_slug)

                # Add vehicle O&M adders to the utility-bill totals
                # Baseline uses ICE adders from the chosen baseline ledger
                baseline_annual_cost += float(baseline_vehicle_adders.loc[county_slug, "ice_operating"]) if county_slug in baseline_vehicle_adders.index else 0.0
                # Scenario uses EV adders from the scenario ledger
                scenario_annual_cost += float(scenario_vehicle_adders.loc[county_slug, "ev_operating"]) if county_slug in scenario_vehicle_adders.index else 0.0
                # Scenario + solar uses the same EV O&M adders (solar doesn't change maint/insurance)
                scenario_solar_annual_cost += float(scenario_vehicle_adders.loc[county_slug, "ev_operating"]) if county_slug in scenario_vehicle_adders.index else 0.0

                savings_scenario_only = baseline_annual_cost - scenario_annual_cost
                savings_with_solar    = baseline_annual_cost - scenario_solar_annual_cost

                # Skip if no cost data available
                if baseline_annual_cost == 0 or (scenario_annual_cost == 0 and scenario_solar_annual_cost == 0):
                    continue

                # Option A: Use Step 14 summary numerators directly, per incentive scenario
                caps = _capital_summary_details(base_input_dir, scenario, housing_type, county_slug)
                if caps['net_outlay_full'] == 0.0 and caps['net_outlay_full_with_pv'] == 0.0:
                    # No summary row for this county; skip
                    continue

                for incentive_scenario in ["full_incentives", "half_incentives", "no_incentives"]:
                    # Select numerator by incentive_scenario
                    if incentive_scenario == "full_incentives":
                        num_no_pv = caps.get('net_outlay_full', 0.0)
                        num_with_pv = caps.get('net_outlay_full_with_pv', 0.0)
                    elif incentive_scenario == "half_incentives":
                        num_no_pv = caps.get('net_outlay_half', 0.0)
                        num_with_pv = caps.get('net_outlay_half_with_pv', 0.0)
                    else:
                        num_no_pv = caps.get('net_outlay_none', 0.0)
                        num_with_pv = caps.get('net_outlay_none_with_pv', 0.0)

                    # 1) Choose which annual savings to use
                    if savings_with_solar > 0:
                        annual_savings = savings_with_solar
                        savings_type = "with_solar"
                    elif savings_scenario_only > 0:
                        annual_savings = savings_scenario_only
                        savings_type = "scenario_only"
                    else:
                        annual_savings = 0.01  # avoid div-by-zero, suggests “very long payback”
                        savings_type = "no_savings"
                        print(f"  Warning: No positive savings for {county} {incentive_scenario}")

                    # 2) Numerator selection from Step 14 summary
                    if savings_type == "with_solar":
                        net_capital_cost = num_with_pv
                    else:
                        net_capital_cost = num_no_pv
                    pv_add = num_with_pv - num_no_pv

                    # 3) Payback
                    payback_years = net_capital_cost / annual_savings if annual_savings > 0 else float('inf')

                    # 4) Diagnostics log for selected counties
                    if _should_log_diagnostic(county_slug):
                        try:
                            pv_capex = caps['pv_capex']
                            storage_capex = caps['storage_capex']
                            pv_inc_full = caps['pv_incentives_full']
                            st_inc_full = caps['storage_incentives_full']
                            pv_net_full = caps['pv_storage_net_full']
                            solar_kw = caps['solar_kw']
                        except Exception:
                            pv_capex = storage_capex = pv_inc_full = st_inc_full = pv_net_full = solar_kw = 0.0

                        price_info = _effective_electricity_price_info(base_input_dir, scenario, housing_type, county_slug)
                        eff_price = price_info.get('effective_price_per_kwh', 0.0)
                        pv_cf = _pv_capacity_factor(base_input_dir, scenario, housing_type, county_slug, solar_kw)
                        self_supply = _self_supply_ratio(base_input_dir, scenario, housing_type, county_slug)
                        peak_share = _peak_period_load_share(base_input_dir, scenario, housing_type, county_slug)
                        util = get_utility_for_county(county_slug)

                        log(
                            at="payback_diagnostic",
                            log_level="debug",
                            county=county,
                            county_slug=county_slug,
                            utility=util,
                            incentive_scenario=incentive_scenario,
                            # Capital summary (no PV)
                            total_capital_cost_electric=round(caps['total_capital_cost_electric'], 2),
                            capital_cost_gas=round(caps['capital_cost_gas'], 2),
                            incentives_full=round(caps['incentives_full'], 2),
                            net_outlay_full=round(caps['net_outlay_full'], 2),
                            net_outlay_no_pv=round(num_no_pv, 2),
                            pv_adder_used=round(pv_add, 2),
                            net_outlay_with_pv=round(net_capital_cost, 2),
                            net_outlay_full_with_pv=round(caps['net_outlay_full_with_pv'], 2),
                            baseline_annual_cost=round(baseline_annual_cost, 2),
                            scenario_annual_cost=round(scenario_annual_cost, 2),
                            scenario_solar_annual_cost=round(scenario_solar_annual_cost, 2),
                            annual_savings_scenario_only=round(savings_scenario_only, 2),
                            annual_savings_with_solar=round(savings_with_solar, 2),
                            annual_savings_used=round(annual_savings, 2),
                            savings_type=savings_type,
                            solar_kw=round(solar_kw, 2),
                            pv_capex=round(pv_capex, 2),
                            storage_capex=round(storage_capex, 2),
                            pv_incentives_full=round(pv_inc_full, 2),
                            storage_incentives_full=round(st_inc_full, 2),
                            pv_storage_net_full=round(pv_net_full, 2),
                            effective_price_per_kwh=round(eff_price, 4),
                            effective_price_tariff=price_info.get('effective_price_tariff'),
                            effective_price_annual_cost=round(price_info.get('effective_price_annual_cost', 0.0), 2),
                            effective_price_annual_kwh=round(price_info.get('effective_price_annual_kwh', 0.0), 2),
                            pv_capacity_factor=round(pv_cf, 4),
                            self_supply_ratio=round(self_supply, 4),
                            peak_period_load_share=round(peak_share, 4),
                            implied_payback_years=round((net_capital_cost / annual_savings) if annual_savings > 0 else float('inf'), 2),
                        )

                    # print(f"    {incentive_scenario}: Capital ${net_capital_cost:.0f}, "
                    #     f"Savings ${annual_savings:.0f} ({savings_type}), "
                    #     f"Payback {payback_years:.1f} years")

                    payback_data.append({
                        'county': county,
                        'county_slug': county_slug,
                        'scenario': scenario,
                        'housing_type': housing_type,
                        'incentive_scenario': incentive_scenario,
                        'baseline_annual_cost': baseline_annual_cost,
                        'scenario_annual_cost': scenario_annual_cost,
                        'scenario_solar_annual_cost': scenario_solar_annual_cost,
                        'annual_savings_scenario_only': savings_scenario_only,
                        'annual_savings_with_solar': savings_with_solar,
                        'annual_savings_used': annual_savings,
                        'savings_type': savings_type,
                        'net_capital_cost': net_capital_cost,
                        'payback_period_years': payback_years
                    })
                    
            except Exception as e:
                print(f"Error processing {county}: {e}")
                continue
        
        return pd.DataFrame(payback_data)
        
    except Exception as e:
        print(f"Error calculating payback periods: {e}")
        log(
            at="step15_payback_periods",
            info="payback_calculation_failed",
            scenario=scenario,
            error=str(e),
            log_level="debug"
        )
        return pd.DataFrame()

def summarize_incremental_capex(capital_costs_df: pd.DataFrame) -> pd.DataFrame:
    df = capital_costs_df.copy()
    df['incentive_scenario'] = df['incentive_scenario'].str.lower()

    elec = (df[df['appliance_category'] == 'electric']
            .groupby(['county', 'incentive_scenario'], as_index=False)['net_cost']
            .sum()
            .rename(columns={'net_cost': 'electric_net'}))

    gas = (df[df['appliance_category'] == 'gas']
           .groupby(['county', 'incentive_scenario'], as_index=False)['base_cost']
           .sum()
           .rename(columns={'base_cost': 'gas_base'}))

    out = (elec.merge(gas, on=['county', 'incentive_scenario'], how='left')
               .fillna({'gas_base': 0.0}))
    out['net_capital_cost_no_pv'] = out['electric_net'] - out['gas_base']
    return out[['county', 'incentive_scenario', 'net_capital_cost_no_pv']]

def process(base_input_dir: str, scenario: str, housing_type: str, counties: list):
    """
    Calculate payback periods for the specified electrification scenario and save to CSV.
    
    Args:
        base_input_dir: Base input directory
        scenario: Electrification scenario name
        housing_type: Housing type
        counties: List of counties to process
    """
    log(
        at="step15_payback_periods",
        info="starting_payback_calculations",
        scenario=scenario,
        housing_type=housing_type,
        counties_count=len(counties)
    )
    
    try:
        # Calculate payback periods
        payback_df = calculate_payback_periods(base_input_dir, scenario, housing_type, counties)
        
        if payback_df.empty:
            log(
                at="step15_payback_periods",
                info="no_payback_data_calculated",
                scenario=scenario
            )
            print(f"No payback data calculated for scenario: {scenario}")
            return
        
        # Save payback data to CSV
        output_dir = os.path.join("data", "results", housing_type)
        os.makedirs(output_dir, exist_ok=True)
        
        csv_path = os.path.join(output_dir, f"payback_periods_{scenario}.csv")
        payback_df.to_csv(csv_path, index=False)
        
        # Get summary stats
        valid_payback = payback_df[payback_df['payback_period_years'] != float('inf')]
        avg_payback = valid_payback['payback_period_years'].mean() if not valid_payback.empty else 0
        incentive_scenarios = payback_df['incentive_scenario'].unique()
        
        log(
            at="step15_payback_periods",
            info="payback_calculations_completed",
            scenario=scenario,
            csv_path=csv_path,
            counties_processed=len(payback_df['county'].unique()),
            incentive_scenarios=len(incentive_scenarios),
            average_payback_years=avg_payback
        )
        
        print(f"Payback period calculations completed for {scenario}")
        print(f"   CSV saved: {csv_path}")
        # print(f"   Counties processed: {len(payback_df['county'].unique())}")
        # print(f"   Incentive scenarios: {len(incentive_scenarios)}")
        # print(f"   Average payback: {avg_payback:.1f} years")
        
        return csv_path
        
    except Exception as e:
        log(
            at="step15_payback_periods",
            info="payback_calculations_failed",
            scenario=scenario,
            error=str(e)
        )
        print(f"Failed to calculate payback periods for {scenario}: {e}")
        raise

if __name__ == "__main__":
    import argparse
    from scenarios import SCENARIOS
    
    parser = argparse.ArgumentParser(description="Calculate payback periods for electrification scenarios")
    parser.add_argument("scenario", 
                       choices=list(SCENARIOS.keys()),
                       help="Electrification scenario to analyze")
    parser.add_argument("--housing-type", default="single-family-detached",
                       help="Housing type (default: single-family-detached)")
    parser.add_argument("--counties", nargs="*", 
                       help="Counties to analyze (default: all counties)")
    
    args = parser.parse_args()
    
    # Use provided counties or default to all California counties
    if args.counties:
        counties = args.counties
    else:
        counties = ["Alameda County"] # norcal_counties + socal_counties + central_counties
    
    process(
        base_input_dir="data/loadprofiles",
        scenario=args.scenario,
        housing_type=args.housing_type,
        counties=counties
    )
