"""
Step 15: Calculate Payback Periods

Calculate payback periods for electrification scenarios based on:
- Capital costs from step15_build_capital_costs_lifetimes_incentives.py
- Annual cost savings from operational cost differences between baseline and scenario

Data Sources:
1. Capital Costs: data/loadprofiles/capital_costs/capital_costs_{scenario}_{housing_type}.csv
   - Generated by step15_build_capital_costs_lifetimes_incentives.py
   - Contains: net_cost by county, appliance, and incentive scenario

2. Annual Costs (Baseline): 
   - Total: {county_dir}/results/totals/RESULTS_total_annual_costs_{county}_{timestamp}.csv
   - Generated by step13_combine_total_annual_costs.py
   
3. Annual Costs (Scenario):
   - Same structure as baseline, but for the specified electrification scenario

Payback Period Calculation:
- Annual Savings = Baseline Annual Costs - Scenario Annual Costs
- Payback Period = Net Capital Costs / Annual Savings (in years)

Output:
- CSV file: data/results/{housing_type}/payback_periods_{scenario}.csv
  Contains payback period data by county and incentive scenario
"""

import os
import pandas as pd
from main_helpers import log, slugify_county_name, norcal_counties, socal_counties, central_counties, get_scenario_path
from helpers.maps_helpers import get_latest_csv_file

# Define which baseline to use for comparison for each scenario
COMPARISON_BASELINE = {
    "baseline_ev_car": "baseline_ice_car",
    "full_electric_ev": "baseline_ice_car",
}

def load_capital_costs(base_input_dir: str, scenario: str, housing_type: str) -> pd.DataFrame:
    """
    Load capital costs data from step15 output.
    
    Args:
        base_input_dir: Base input directory 
        scenario: Electrification scenario name
        housing_type: Housing type
        
    Returns:
        DataFrame with capital costs by county and incentive scenario
    """
    capital_costs_dir = os.path.join(base_input_dir, "capital_costs")
    csv_filename = f"capital_costs_{scenario}_{housing_type.replace('-', '_')}.csv"
    csv_path = os.path.join(capital_costs_dir, csv_filename)
    
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Capital costs file not found: {csv_path}")
    
    df = pd.read_csv(csv_path)
    log(
        at="load_capital_costs",
        info="capital_costs_loaded",
        rows_count=len(df),
        csv_path=csv_path
    )
    return df

def load_annual_costs(base_input_dir: str, county: str, scenario: str, housing_type: str, with_solar: bool = False) -> float:
    """
    Load annual total costs for a county and scenario, following the same pattern as capital_costs_helper.py.
    
    Args:
        base_input_dir: Base input directory
        county: Full county name (e.g., 'Alameda County')
        scenario: Scenario name ('baseline' or electrification scenario)
        housing_type: Housing type
        with_solar: Whether to load from solarstorage directory
        
    Returns:
        Annual total cost for the scenario
    """
    county_slug = slugify_county_name(county)
    
    if with_solar:
        # Load from solarstorage results directory
        results_dir = os.path.join(base_input_dir, scenario, housing_type, county_slug, "results", "solarstorage")
        expected_scenario = f"{scenario}.solarstorage"
    else:
        # Load from totals results directory  
        results_dir = os.path.join(base_input_dir, scenario, housing_type, county_slug, "results", "totals")
        expected_scenario = scenario
    
    if not os.path.exists(results_dir):
        log(
            at="load_annual_costs",
            info="results_directory_not_found",
            directory=results_dir
        )
        return 0.0
    
    try:
        # Get latest total annual costs file
        file_path = get_latest_csv_file(results_dir, f"RESULTS_total_annual_costs_{county_slug}_")
        df = pd.read_csv(file_path, index_col="scenario")
        
        if expected_scenario in df.index:
            # Use first column (usually the primary rate plan like total.PG&E.E-TOU-D+PG&E.G-1)
            cost_value = df.loc[expected_scenario]
            if hasattr(cost_value, 'iloc'):
                return float(cost_value.iloc[0])
            else:
                return float(cost_value)
        else:
            log(
                at="load_annual_costs",
                info="scenario_not_found",
                expected_scenario=expected_scenario,
                file_path=file_path,
                available_scenarios=list(df.index)
            )
            return 0.0
            
    except Exception as e:
        log(
            at="load_annual_costs",
            info="annual_costs_load_failed",
            county=county,
            scenario=scenario,
            with_solar=with_solar,
            error=str(e)
        )
        return 0.0

def load_pv_net_adders(base_input_dir: str, scenario: str, housing_type: str) -> pd.DataFrame:
    """
    Reads capital_costs_summary_with_pv_{scenario}_{housing_type}.csv
    and returns (county_slug, pv_storage_net_full/half/none).
    If file missing, returns empty df (treated as zeros downstream).
    """
    capital_costs_dir = os.path.join(base_input_dir, "capital_costs")
    fname = f"capital_costs_summary_with_pv_{scenario}_{housing_type.replace('-', '_')}.csv"
    path = os.path.join(capital_costs_dir, fname)

    if not os.path.exists(path):
        log(at="load_pv_net_adders", info="pv_summary_not_found", csv_path=path)
        return pd.DataFrame(columns=[
            'county_slug',
            'pv_storage_net_full', 'pv_storage_net_half', 'pv_storage_net_none'
        ])

    df = pd.read_csv(path)
    # Keep only what we need; if columns are missing, fill zeros
    needed = ['county_slug',
              'pv_storage_net_full', 'pv_storage_net_half', 'pv_storage_net_none']
    for col in needed:
        if col not in df.columns:
            df[col] = 0.0
    log(at="load_pv_net_adders", info="pv_summary_loaded", rows_count=len(df), csv_path=path)
    
    return df[needed]

def pv_adder_for(county_slug: str, incentive_scenario: str, pv_net_df: pd.DataFrame) -> float:
    if pv_net_df.empty:
        return 0.0
    row = pv_net_df[pv_net_df['county_slug'] == county_slug]
    if row.empty:
        return 0.0
    key = str(incentive_scenario).lower()
    col_map = {
        'full_incentives': 'pv_storage_net_full',
        'half_incentives': 'pv_storage_net_half',
        'none_incentives': 'pv_storage_net_none',
    }
    col = col_map.get(key)
    return float(row.iloc[0][col]) if col in row.columns else 0.0

VEHICLE_PREFIX = "RESULTS_vehicle_annual_costs"

def get_costs_from_vehicle(county_dir):
    """Load vehicle costs from CSV file."""
    vehicle_dir = os.path.join(county_dir, "results", "vehicle")
    if not os.path.exists(vehicle_dir):
        # Return empty DataFrame if no vehicle costs exist
        return pd.DataFrame()
    
    county = os.path.basename(county_dir)
    prefix = f"{VEHICLE_PREFIX}_{county}_"
    
    try:
        latest_file = get_latest_csv_file(vehicle_dir, prefix)
        return pd.read_csv(latest_file, index_col="scenario")
    except FileNotFoundError:
        # Return empty DataFrame if no vehicle costs file found
        return pd.DataFrame()

def load_annual_costs_for_county(base_input_dir: str, county: str, scenario: str, housing_type: str):
    # 1. Baseline costs (no electrification)
    baseline_annual_cost = load_annual_costs(base_input_dir, county, "baseline", housing_type, with_solar=False)
    
    # 2. Scenario costs (electrification only, no solar)
    scenario_annual_cost = load_annual_costs(base_input_dir, county, scenario, housing_type, with_solar=False)
    
    # 3. Scenario + solar costs (electrification + solar+storage)
    scenario_solar_annual_cost = load_annual_costs(base_input_dir, county, scenario, housing_type, with_solar=True)
    
    if baseline_annual_cost == 0:
        log(at="load_annual_costs_for_county", info="missing_baseline_cost_data", county=county)
        return baseline_annual_cost, scenario_annual_cost, scenario_solar_annual_cost, 0.0, 0.0
        
    if scenario_annual_cost == 0 or scenario_solar_annual_cost == 0:
        log(at="load_annual_costs_for_county", info="missing_scenario_cost_data", county=county)
        return baseline_annual_cost, scenario_annual_cost, scenario_solar_annual_cost, 0.0, 0.0
    
    # --- Vehicle O&M costs ---
    county_dir = os.path.join(base_input_dir, scenario, housing_type, county)
    vehicle_df = get_costs_from_vehicle(county_dir)

    if not vehicle_df.empty:
        if scenario == "baseline_ev_car":
            # Add EV costs to baseline and scenario costs
            ev_cost = vehicle_df.loc[scenario, "vehicle.operating.ev_maintenance_insurance"]
            baseline_annual_cost += ev_cost
            scenario_annual_cost += ev_cost
            scenario_solar_annual_cost += ev_cost
        elif scenario == "baseline_ice_car":
            ice_cost = vehicle_df.loc[scenario, "vehicle.operating.ice_maintenance_insurance_fuel"]
            baseline_annual_cost += ice_cost
            scenario_annual_cost += ice_cost
            scenario_solar_annual_cost += ice_cost

    # Calculate annual savings (baseline - scenario)
    savings_scenario_only = baseline_annual_cost - scenario_annual_cost
    savings_with_solar = baseline_annual_cost - scenario_solar_annual_cost
    
    return baseline_annual_cost, scenario_annual_cost, scenario_solar_annual_cost, savings_scenario_only, savings_with_solar
    
def calculate_net_capital_cost(capital_summary: pd.DataFrame, county: str) -> pd.DataFrame:
    return capital_summary[capital_summary['county'] == county]

def summarize_incremental_capex_against_baseline(
    scen_df: pd.DataFrame, base_df: pd.DataFrame
) -> pd.DataFrame:
    """
    Compare electric net costs from the scenario against gas base costs
    from the chosen baseline (e.g., baseline_ice_car for EV scenarios).
    """
    s = scen_df.copy()
    b = base_df.copy()
    s['incentive_scenario'] = s['incentive_scenario'].str.lower()
    b['incentive_scenario'] = b['incentive_scenario'].str.lower()

    # scenario net
    scenario_net = (
        s.groupby(['county', 'county_slug', 'incentive_scenario'], as_index=False)['net_cost']
        .sum()
    )

    # baseline net
    baseline_net = (
        b.groupby(['county', 'county_slug', 'incentive_scenario'], as_index=False)['net_cost']
        .sum()
    )

    out = scenario_net.merge(
        baseline_net,
        on=['county', 'county_slug', 'incentive_scenario'],
        how='outer'  # keep all combos, even if missing in one side
    ).fillna(0.0)
    out['net_capital_cost_no_pv'] = scenario_net['net_cost'] - baseline_net['net_cost']

    return out[['county', 'county_slug', 'incentive_scenario','net_capital_cost_no_pv']]

def detect_vehicle_kind(ledger_df: pd.DataFrame) -> str:
    """Return 'ev' if scenario has vehicle_charging, 'ice' if vehicle_fuel, else 'none'."""
    has_ev  = ((ledger_df['appliance_category'] == 'electric') & (ledger_df['appliance_type'] == 'vehicle_charging')).any()
    has_ice = ((ledger_df['appliance_category'] == 'gas')     & (ledger_df['appliance_type'] == 'vehicle_fuel')).any()
    if has_ev:  return 'ev'
    if has_ice: return 'ice'
    return 'none'

def calculate_payback_periods(base_input_dir: str, scenario: str, housing_type: str, counties: list) -> pd.DataFrame:
    """
    Calculate payback periods for all counties and incentive scenarios.
    
    Args:
        base_input_dir: Base input directory
        scenario: Electrification scenario name  
        housing_type: Housing type
        counties: List of counties to process
        
    Returns:
        DataFrame with payback period data
    """
    try:
        scenario_df = load_capital_costs(base_input_dir, scenario, housing_type)
        baseline_name = COMPARISON_BASELINE.get(scenario, "baseline")
        baseline_df  = load_capital_costs(base_input_dir, baseline_name, housing_type)

        # Calculate capital cost difference between scenarios
        capital_summary  = summarize_incremental_capex_against_baseline(scenario_df, baseline_df)
        
        pv_net_df = load_pv_net_adders(base_input_dir, scenario, housing_type)
        log(
            at="calculate_payback_periods",
            info="capital_costs_summary_created",
            combinations_count=len(capital_summary)
        )
        
        payback_data = []
        
        for county in counties:
            try:
                county_slug = slugify_county_name(county)
                
                # Calculate annual costs and savings
                baseline_annual_cost, scenario_annual_cost, scenario_solar_annual_cost, savings_scenario_only, savings_with_solar = load_annual_costs_for_county(
                    base_input_dir, county, scenario, housing_type
                )

                savings_scenario_only = baseline_annual_cost - scenario_annual_cost
                savings_with_solar    = baseline_annual_cost - scenario_solar_annual_cost

                # Skip if no cost data available
                if baseline_annual_cost == 0 or (scenario_annual_cost == 0 and scenario_solar_annual_cost == 0):
                    continue
                
                # Get capital costs for this county
                county_capital = calculate_net_capital_cost(capital_summary, county)
                
                if county_capital.empty:
                    continue
                
                for _, capital_row in county_capital.iterrows():
                    incentive_scenario = str(capital_row['incentive_scenario']).lower()
                    county_slug = slugify_county_name(county)

                    inc_row = capital_summary[
                        (capital_summary['county'] == county) &
                        (capital_summary['incentive_scenario'].str.lower() == incentive_scenario)
                    ]
                    if inc_row.empty:
                        continue

                    net_cap_no_pv = float(inc_row.iloc[0]['net_capital_cost_no_pv'])

                    # 1) Choose which annual savings to use
                    if savings_with_solar > 0:
                        annual_savings = savings_with_solar
                        savings_type = "with_solar"
                    elif savings_scenario_only > 0:
                        annual_savings = savings_scenario_only
                        savings_type = "scenario_only"
                    else:
                        annual_savings = 0.01  # avoid div-by-zero, suggests “very long payback”
                        savings_type = "no_savings"
                        print(f"  Warning: No positive savings for {county} {incentive_scenario}")

                    # 2) Adjust capex if we’re using with-solar savings
                    pv_add = pv_adder_for(county_slug, incentive_scenario, pv_net_df)
                    if savings_type == "with_solar":
                        net_capital_cost = net_cap_no_pv + pv_add
                    else:
                        net_capital_cost = net_cap_no_pv

                    # 3) Payback
                    payback_years = net_capital_cost / annual_savings if annual_savings > 0 else float('inf')
                    payback_years_no_pv = net_cap_no_pv / annual_savings

                    payback_data.append({
                        'county': county,
                        'county_slug': county_slug,
                        'scenario': scenario,
                        'housing_type': housing_type,
                        'incentive_scenario': incentive_scenario,
                        'baseline_annual_cost': baseline_annual_cost,
                        'scenario_annual_cost': scenario_annual_cost,
                        'scenario_solar_annual_cost': scenario_solar_annual_cost,
                        'annual_savings_scenario_only': savings_scenario_only,
                        'annual_savings_with_solar': savings_with_solar,
                        'annual_savings_used': annual_savings,
                        'savings_type': savings_type,
                        'net_cap_cost_difference_no_pv': net_cap_no_pv,
                        'pv_cap_costs': pv_add,
                        'net_cap_cost_difference_with_pv': net_capital_cost,
                        'payback_period_years': payback_years,
                        'payback_years_no_pv': payback_years_no_pv,
                    })
                    
            except Exception as e:
                print(f"Error processing {county}: {e}")
                continue
        
        return pd.DataFrame(payback_data)
        
    except Exception as e:
        print(f"Error calculating payback periods: {e}")
        log(
            at="step16_payback_periods",
            info="payback_calculation_failed",
            scenario=scenario,
            error=str(e)
        )
        return pd.DataFrame()

def summarize_incremental_capex(capital_costs_df: pd.DataFrame) -> pd.DataFrame:
    df = capital_costs_df.copy()
    df['incentive_scenario'] = df['incentive_scenario'].str.lower()

    elec = (df[df['appliance_category'] == 'electric']
            .groupby(['county', 'incentive_scenario'], as_index=False)['net_cost']
            .sum()
            .rename(columns={'net_cost': 'electric_net'}))

    gas = (df[df['appliance_category'] == 'gas']
           .groupby(['county', 'incentive_scenario'], as_index=False)['base_cost']
           .sum()
           .rename(columns={'base_cost': 'gas_base'}))

    out = (elec.merge(gas, on=['county', 'incentive_scenario'], how='left')
               .fillna({'gas_base': 0.0}))
    out['net_capital_cost_no_pv'] = out['electric_net'] - out['gas_base']
    return out[['county', 'incentive_scenario', 'net_capital_cost_no_pv']]

def process(base_input_dir: str, scenario: str, housing_type: str, counties: list):
    """
    Calculate payback periods for the specified electrification scenario and save to CSV.
    
    Args:
        base_input_dir: Base input directory
        scenario: Electrification scenario name
        housing_type: Housing type
        counties: List of counties to process
    """
    log(
        at="step16_payback_periods",
        info="starting_payback_calculations",
        scenario=scenario,
        housing_type=housing_type,
        counties_count=len(counties)
    )
    
    try:
        # Calculate payback periods
        payback_df = calculate_payback_periods(base_input_dir, scenario, housing_type, counties)
        
        if payback_df.empty:
            log(
                at="step16_payback_periods",
                info="no_payback_data_calculated",
                scenario=scenario
            )
            print(f"No payback data calculated for scenario: {scenario}")
            return
        
        # Save payback data to CSV
        output_dir = os.path.join("data", "results", housing_type)
        os.makedirs(output_dir, exist_ok=True)
        
        csv_path = os.path.join(output_dir, f"payback_periods_{scenario}.csv")
        payback_df.to_csv(csv_path, index=False)
        
        # Get summary stats
        valid_payback = payback_df[payback_df['payback_period_years'] != float('inf')]
        avg_payback = valid_payback['payback_period_years'].mean() if not valid_payback.empty else 0
        incentive_scenarios = payback_df['incentive_scenario'].unique()
        
        log(
            at="step16_payback_periods",
            info="payback_calculations_completed",
            scenario=scenario,
            csv_path=csv_path,
            counties_processed=len(payback_df['county'].unique()),
            incentive_scenarios=len(incentive_scenarios),
            average_payback_years=avg_payback
        )
        
        print(f"Payback period calculations completed for {scenario}")
        print(f"   CSV saved: {csv_path}")
        # print(f"   Counties processed: {len(payback_df['county'].unique())}")
        # print(f"   Incentive scenarios: {len(incentive_scenarios)}")
        # print(f"   Average payback: {avg_payback:.1f} years")
        
        return csv_path
        
    except Exception as e:
        log(
            at="step16_payback_periods",
            info="payback_calculations_failed",
            scenario=scenario,
            error=str(e)
        )
        print(f"Failed to calculate payback periods for {scenario}: {e}")
        raise

if __name__ == "__main__":
    import argparse
    from scenarios import SCENARIOS
    
    parser = argparse.ArgumentParser(description="Calculate payback periods for electrification scenarios")
    parser.add_argument("scenario", 
                       choices=list(SCENARIOS.keys()),
                       help="Electrification scenario to analyze")
    parser.add_argument("--housing-type", default="single-family-detached",
                       help="Housing type (default: single-family-detached)")
    parser.add_argument("--counties", nargs="*", 
                       help="Counties to analyze (default: all counties)")
    
    args = parser.parse_args()
    
    # Use provided counties or default to all California counties
    if args.counties:
        counties = args.counties
    else:
        counties = norcal_counties + socal_counties + central_counties
    
    process(
        base_input_dir="data/loadprofiles",
        scenario=args.scenario,
        housing_type=args.housing_type,
        counties=counties
    )