"""
Step 16: Calculate Payback Periods

Calculate payback periods for electrification scenarios based on:
- Capital costs from step15_build_capital_costs_lifetimes_incentives.py
- Annual cost savings from operational cost differences between baseline and scenario

Data Sources:
1. Capital Costs: data/loadprofiles/capital_costs/capital_costs_{scenario}_{housing_type}.csv
   - Generated by step15_build_capital_costs_lifetimes_incentives.py
   - Contains: net_cost by county, appliance, and incentive scenario

2. Annual Costs (Baseline): 
   - Total: {county_dir}/results/totals/RESULTS_total_annual_costs_{county}_{timestamp}.csv
   - Generated by step13_combine_total_annual_costs.py
   
3. Annual Costs (Scenario):
   - Same structure as baseline, but for the specified electrification scenario

Payback Period Calculation:
- Annual Savings = Baseline Annual Costs - Scenario Annual Costs
- Payback Period = Net Capital Costs / Annual Savings (in years)

Output:
- CSV file: data/results/{housing_type}/payback_periods_{scenario}.csv
  Contains payback period data by county and incentive scenario
"""

import os
import pandas as pd
import numpy as np
from collections import defaultdict
from main_helpers import log, slugify_county_name, norcal_counties, socal_counties, central_counties, get_scenario_path
from helpers.maps_helpers import get_latest_csv_file
from helpers.capital_costs_helper import load_electrified_assets
from step17_cris_capital_costs import CAPITAL_COSTS_CRIS

def load_capital_costs(base_input_dir: str, scenario: str, housing_type: str) -> pd.DataFrame:
    """
    Load capital costs data from step15 output.
    
    Args:
        base_input_dir: Base input directory 
        scenario: Electrification scenario name
        housing_type: Housing type
        
    Returns:
        DataFrame with capital costs by county and incentive scenario
    """
    capital_costs_dir = os.path.join(base_input_dir, "capital_costs")
    csv_filename = f"capital_costs_{scenario}_{housing_type.replace('-', '_')}.csv"
    csv_path = os.path.join(capital_costs_dir, csv_filename)
    
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Capital costs file not found: {csv_path}")
    
    df = pd.read_csv(csv_path)
    print(f"Loaded capital costs: {len(df)} rows from {csv_path}")
    return df

def load_annual_costs(base_input_dir: str, county: str, scenario: str, housing_type: str, with_solar: bool = False) -> float:
    """
    Load annual total costs for a county and scenario, following the same pattern as capital_costs_helper.py.
    
    Args:
        base_input_dir: Base input directory
        county: Full county name (e.g., 'Alameda County')
        scenario: Scenario name ('baseline' or electrification scenario)
        housing_type: Housing type
        with_solar: Whether to load from solarstorage directory
        
    Returns:
        Annual total cost for the scenario
    """
    county_slug = slugify_county_name(county)
    
    if with_solar:
        # Load from solarstorage results directory
        results_dir = os.path.join(base_input_dir, scenario, housing_type, county_slug, "results", "solarstorage")
        expected_scenario = f"{scenario}.solarstorage"
    else:
        # Load from totals results directory  
        results_dir = os.path.join(base_input_dir, scenario, housing_type, county_slug, "results", "totals")
        expected_scenario = scenario
    
    if not os.path.exists(results_dir):
        print(f"Warning: Results directory not found: {results_dir}")
        return 0.0
    
    try:
        # Get latest total annual costs file
        file_path = get_latest_csv_file(results_dir, f"RESULTS_total_annual_costs_{county_slug}_")
        df = pd.read_csv(file_path, index_col="scenario")
        
        if expected_scenario in df.index:
            # Use first column (usually the primary rate plan like total.PG&E.E-TOU-D+PG&E.G-1)
            cost_value = df.loc[expected_scenario]
            if hasattr(cost_value, 'iloc'):
                return float(cost_value.iloc[0])
            else:
                return float(cost_value)
        else:
            print(f"Warning: Scenario {expected_scenario} not found in {file_path}")
            print(f"Available scenarios: {list(df.index)}")
            return 0.0
            
    except Exception as e:
        print(f"Warning: Failed to load annual costs for {county}/{scenario} (solar={with_solar}): {e}")
        return 0.0

def load_solar_capacity_data(base_input_dir: str, scenario: str, housing_type: str) -> dict:
    """
    Load solar capacity data for counties from electrified assets CSV.
    
    Args:
        base_input_dir: Base input directory
        scenario: Electrification scenario name
        housing_type: Housing type
        
    Returns:
        Dictionary mapping county slug to solar capacity in kW
    """
    try:
        scenario_path = get_scenario_path(base_input_dir, scenario, housing_type)
        assets_mapping = load_electrified_assets(scenario_path)
        
        # Convert county names to slugs for consistency
        slug_mapping = {}
        for county_name, solar_kw in assets_mapping.items():
            county_slug = slugify_county_name(county_name)
            slug_mapping[county_slug] = solar_kw
        
        print(f"Loaded solar capacity data: {len(slug_mapping)} counties")
        return slug_mapping
        
    except Exception as e:
        print(f"Warning: Could not load solar capacity data: {e}")
        return {}

def calculate_solar_storage_capital_costs(solar_kw: float) -> dict:
    """
    Calculate solar and storage capital costs based on CAPITAL_COSTS_CRIS structure.
    
    Args:
        solar_kw: Solar system capacity in kW
        
    Returns:
        Dictionary with solar and storage cost breakdown
    """
    try:
        # Extract solar cost parameters from CAPITAL_COSTS_CRIS
        solar_config = CAPITAL_COSTS_CRIS["solar"]["panel"]
        storage_config = CAPITAL_COSTS_CRIS["storage"]["tesla_powerwall_3"]
        
        # Solar costs
        dollars_per_watt = solar_config["base"]["value"]  # $2.8/W
        installation_markup = solar_config["markup"]["installation_labor"]["value"] / 100  # 0%
        design_markup = solar_config["markup"]["design_engineering"]["value"] / 100  # 0%
        
        # Calculate solar costs
        panel_cost = solar_kw * 1000 * dollars_per_watt  # Convert kW to W
        total_solar_cost = panel_cost * (1 + installation_markup + design_markup)
        
        # Storage costs (Tesla Powerwall 3)
        storage_cost = storage_config["base"]["value"]  # $16,853
        storage_capacity = storage_config["capacity_kwh"]  # 13.5 kWh
        
        # Total system cost before incentives
        total_system_cost = total_solar_cost + storage_cost
        
        # Apply federal tax credit (30% through 2032)
        federal_tax_credit = total_system_cost * 0.30
        
        # Net cost after incentives
        net_cost = total_system_cost - federal_tax_credit
        
        return {
            "solar_kw": solar_kw,
            "panel_cost": panel_cost,
            "total_solar_cost": total_solar_cost,
            "storage_cost": storage_cost,
            "storage_capacity_kwh": storage_capacity,
            "total_system_cost_before_incentives": total_system_cost,
            "federal_tax_credit": federal_tax_credit,
            "net_solar_storage_cost": net_cost
        }
        
    except Exception as e:
        print(f"Error calculating solar/storage costs: {e}")
        return {
            "solar_kw": solar_kw,
            "net_solar_storage_cost": 0.0
        }

def calculate_payback_periods(base_input_dir: str, scenario: str, housing_type: str, counties: list) -> pd.DataFrame:
    """
    Calculate payback periods for all counties and incentive scenarios.
    
    Args:
        base_input_dir: Base input directory
        scenario: Electrification scenario name  
        housing_type: Housing type
        counties: List of counties to process
        
    Returns:
        DataFrame with payback period data
    """
    try:
        # Load capital costs data from step15 (electrification appliances only)
        capital_costs_df = load_capital_costs(base_input_dir, scenario, housing_type)
        print(f"Loaded electrification capital costs: {len(capital_costs_df)} rows")
        
        if capital_costs_df.empty:
            print(f"No capital costs data found for scenario: {scenario}")
            return pd.DataFrame()
        
        # Group capital costs by county and incentive scenario
        capital_summary = capital_costs_df.groupby(['county', 'incentive_scenario'])['net_cost'].sum().reset_index()
        print(f"Electrification capital costs summary: {len(capital_summary)} county-incentive combinations")
        
        # Load solar capacity data for solar/storage capital costs
        solar_capacity_data = load_solar_capacity_data(base_input_dir, scenario, housing_type)
        print(f"Loaded solar capacity data: {len(solar_capacity_data)} counties")
        
        payback_data = []
        
        for county in counties:
            try:
                # 1. Baseline costs (no electrification)
                baseline_annual_cost = load_annual_costs(base_input_dir, county, "baseline", housing_type, with_solar=False)
                
                # 2. Scenario costs (electrification only, no solar)
                scenario_annual_cost = load_annual_costs(base_input_dir, county, scenario, housing_type, with_solar=False)
                
                # 3. Scenario + solar costs (electrification + solar+storage)
                scenario_solar_annual_cost = load_annual_costs(base_input_dir, county, scenario, housing_type, with_solar=True)
                
                if baseline_annual_cost == 0:
                    print(f"Warning: Missing baseline annual cost data for {county}")
                    continue
                    
                if scenario_annual_cost == 0 or scenario_solar_annual_cost == 0:
                    print(f"Warning: Missing scenario annual cost data for {county}")
                    continue
                
                # Calculate annual savings (baseline - scenario)
                savings_scenario_only = baseline_annual_cost - scenario_annual_cost
                savings_with_solar = baseline_annual_cost - scenario_solar_annual_cost
                
                print(f"{county}:")
                print(f"  Baseline: ${baseline_annual_cost:.0f}")
                print(f"  {scenario} only: ${scenario_annual_cost:.0f} (savings: ${savings_scenario_only:.0f})")
                print(f"  {scenario} + solar: ${scenario_solar_annual_cost:.0f} (savings: ${savings_with_solar:.0f})")
                
                # Get capital costs for this county
                county_capital = capital_summary[capital_summary['county'].str.contains(county.replace(' County', ''), case=False, na=False)]
                
                if county_capital.empty:
                    print(f"Warning: No capital costs found for {county}")
                    continue
                
                # Get solar capacity for this county
                county_slug = slugify_county_name(county)
                solar_kw = solar_capacity_data.get(county_slug, 0.0)
                
                # Calculate solar/storage capital costs if solar capacity exists
                solar_storage_costs = calculate_solar_storage_capital_costs(solar_kw) if solar_kw > 0 else None
                
                print(f"  Solar capacity: {solar_kw:.1f} kW")
                if solar_storage_costs:
                    print(f"  Solar/storage capital cost: ${solar_storage_costs['net_solar_storage_cost']:.0f}")
                
                # Calculate payback for each incentive scenario
                for _, capital_row in county_capital.iterrows():
                    incentive_scenario = capital_row['incentive_scenario']
                    electrification_capital_cost = capital_row['net_cost']
                    
                    # Total capital costs (electrification + solar/storage)
                    if solar_storage_costs and savings_with_solar > savings_scenario_only:
                        # Use solar+storage scenario
                        total_capital_cost = electrification_capital_cost + solar_storage_costs['net_solar_storage_cost']
                        annual_savings = savings_with_solar
                        savings_type = "with_solar"
                    elif savings_scenario_only > 0:
                        # Use electrification-only scenario
                        total_capital_cost = electrification_capital_cost
                        annual_savings = savings_scenario_only 
                        savings_type = "scenario_only"
                    else:
                        # No positive savings available - use electrification costs with minimal savings
                        total_capital_cost = electrification_capital_cost
                        annual_savings = 0.01
                        savings_type = "no_savings"
                        print(f"  Warning: No positive savings for {county} {incentive_scenario}")
                    
                    # Calculate payback period in years
                    payback_years = total_capital_cost / annual_savings if annual_savings > 0 else float('inf')
                    
                    print(f"    {incentive_scenario}: Electrification ${electrification_capital_cost:.0f}, Total Capital ${total_capital_cost:.0f}, Savings ${annual_savings:.0f} ({savings_type}), Payback {payback_years:.1f} years")
                    
                    payback_data.append({
                        'county': county,
                        'county_slug': slugify_county_name(county),
                        'scenario': scenario,
                        'housing_type': housing_type,
                        'incentive_scenario': incentive_scenario,
                        'baseline_annual_cost': baseline_annual_cost,
                        'scenario_annual_cost': scenario_annual_cost,
                        'scenario_solar_annual_cost': scenario_solar_annual_cost,
                        'annual_savings_scenario_only': savings_scenario_only,
                        'annual_savings_with_solar': savings_with_solar,
                        'annual_savings_used': annual_savings,
                        'savings_type': savings_type,
                        'electrification_capital_cost': electrification_capital_cost,
                        'solar_storage_capital_cost': solar_storage_costs['net_solar_storage_cost'] if solar_storage_costs else 0.0,
                        'solar_capacity_kw': solar_kw,
                        'total_capital_cost': total_capital_cost,
                        'net_capital_cost': total_capital_cost,  # Keep for backward compatibility
                        'payback_period_years': payback_years
                    })
                    
            except Exception as e:
                print(f"Error processing {county}: {e}")
                continue
        
        return pd.DataFrame(payback_data)
        
    except Exception as e:
        print(f"Error calculating payback periods: {e}")
        log(
            at="step16_payback_periods",
            info="payback_calculation_failed",
            scenario=scenario,
            error=str(e)
        )
        return pd.DataFrame()

def process(base_input_dir: str, scenario: str, housing_type: str, counties: list):
    """
    Calculate payback periods for the specified electrification scenario and save to CSV.
    
    Args:
        base_input_dir: Base input directory
        scenario: Electrification scenario name
        housing_type: Housing type
        counties: List of counties to process
    """
    log(
        at="step16_payback_periods",
        info="starting_payback_calculations",
        scenario=scenario,
        housing_type=housing_type,
        counties_count=len(counties)
    )
    
    try:
        # Calculate payback periods
        payback_df = calculate_payback_periods(base_input_dir, scenario, housing_type, counties)
        
        if payback_df.empty:
            log(
                at="step16_payback_periods",
                info="no_payback_data_calculated",
                scenario=scenario
            )
            print(f"No payback data calculated for scenario: {scenario}")
            return
        
        # Save payback data to CSV
        output_dir = os.path.join("data", "results", housing_type)
        os.makedirs(output_dir, exist_ok=True)
        
        csv_path = os.path.join(output_dir, f"payback_periods_{scenario}.csv")
        payback_df.to_csv(csv_path, index=False)
        
        # Get summary stats
        valid_payback = payback_df[payback_df['payback_period_years'] != float('inf')]
        avg_payback = valid_payback['payback_period_years'].mean() if not valid_payback.empty else 0
        incentive_scenarios = payback_df['incentive_scenario'].unique()
        
        log(
            at="step16_payback_periods",
            info="payback_calculations_completed",
            scenario=scenario,
            csv_path=csv_path,
            counties_processed=len(payback_df['county'].unique()),
            incentive_scenarios=len(incentive_scenarios),
            average_payback_years=avg_payback
        )
        
        print(f"Payback period calculations completed for {scenario}")
        print(f"   CSV saved: {csv_path}")
        print(f"   Counties processed: {len(payback_df['county'].unique())}")
        print(f"   Incentive scenarios: {len(incentive_scenarios)}")
        print(f"   Average payback: {avg_payback:.1f} years")
        
        return csv_path
        
    except Exception as e:
        log(
            at="step16_payback_periods",
            info="payback_calculations_failed",
            scenario=scenario,
            error=str(e)
        )
        print(f"Failed to calculate payback periods for {scenario}: {e}")
        raise

if __name__ == "__main__":
    import argparse
    from scenarios import SCENARIOS
    
    parser = argparse.ArgumentParser(description="Calculate payback periods for electrification scenarios")
    parser.add_argument("scenario", 
                       choices=list(SCENARIOS.keys()),
                       help="Electrification scenario to analyze")
    parser.add_argument("--housing-type", default="single-family-detached",
                       help="Housing type (default: single-family-detached)")
    parser.add_argument("--counties", nargs="*", 
                       help="Counties to analyze (default: all counties)")
    
    args = parser.parse_args()
    
    # Use provided counties or default to all California counties
    if args.counties:
        counties = args.counties
    else:
        counties = norcal_counties + socal_counties + central_counties
    
    process(
        base_input_dir="data/loadprofiles",
        scenario=args.scenario,
        housing_type=args.housing_type,
        counties=counties
    )