"""
Step 16: Calculate Payback Periods

Calculate payback periods for electrification scenarios based on:
- Capital costs from step15_build_capital_costs_lifetimes_incentives.py
- Annual cost savings from operational cost differences between baseline and scenario

Data Sources:
1. Capital Costs: data/loadprofiles/capital_costs/capital_costs_{scenario}_{housing_type}.csv
   - Generated by step15_build_capital_costs_lifetimes_incentives.py
   - Contains: net_cost by county, appliance, and incentive scenario

2. Annual Costs (Baseline): 
   - Total: {county_dir}/results/totals/RESULTS_total_annual_costs_{county}_{timestamp}.csv
   - Generated by step13_combine_total_annual_costs.py
   
3. Annual Costs (Scenario):
   - Same structure as baseline, but for the specified electrification scenario

Payback Period Calculation:
- Annual Savings = Baseline Annual Costs - Scenario Annual Costs
- Payback Period = Net Capital Costs / Annual Savings (in years)

Output:
- CSV file: data/results/{housing_type}/payback_periods_{scenario}.csv
  Contains payback period data by county and incentive scenario
"""

import os
import pandas as pd
import numpy as np
from collections import defaultdict
from main_helpers import log, slugify_county_name, norcal_counties, socal_counties, central_counties, get_scenario_path
from helpers.maps_helpers import get_latest_csv_file

def load_capital_costs(base_input_dir: str, scenario: str, housing_type: str) -> pd.DataFrame:
    """
    Load capital costs data from step15 output.
    
    Args:
        base_input_dir: Base input directory 
        scenario: Electrification scenario name
        housing_type: Housing type
        
    Returns:
        DataFrame with capital costs by county and incentive scenario
    """
    capital_costs_dir = os.path.join(base_input_dir, "capital_costs")
    csv_filename = f"capital_costs_{scenario}_{housing_type.replace('-', '_')}.csv"
    csv_path = os.path.join(capital_costs_dir, csv_filename)
    
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Capital costs file not found: {csv_path}")
    
    df = pd.read_csv(csv_path)
    log(
        at="load_capital_costs",
        info="capital_costs_loaded",
        rows_count=len(df),
        csv_path=csv_path
    )
    return df

def load_annual_costs(base_input_dir: str, county: str, scenario: str, housing_type: str, with_solar: bool = False) -> float:
    """
    Load annual total costs for a county and scenario, following the same pattern as capital_costs_helper.py.
    
    Args:
        base_input_dir: Base input directory
        county: Full county name (e.g., 'Alameda County')
        scenario: Scenario name ('baseline' or electrification scenario)
        housing_type: Housing type
        with_solar: Whether to load from solarstorage directory
        
    Returns:
        Annual total cost for the scenario
    """
    county_slug = slugify_county_name(county)
    
    if with_solar:
        # Load from solarstorage results directory
        results_dir = os.path.join(base_input_dir, scenario, housing_type, county_slug, "results", "solarstorage")
        expected_scenario = f"{scenario}.solarstorage"
    else:
        # Load from totals results directory  
        results_dir = os.path.join(base_input_dir, scenario, housing_type, county_slug, "results", "totals")
        expected_scenario = scenario
    
    if not os.path.exists(results_dir):
        log(
            at="load_annual_costs",
            info="results_directory_not_found",
            directory=results_dir
        )
        return 0.0
    
    try:
        # Get latest total annual costs file
        file_path = get_latest_csv_file(results_dir, f"RESULTS_total_annual_costs_{county_slug}_")
        df = pd.read_csv(file_path, index_col="scenario")
        
        if expected_scenario in df.index:
            # Use first column (usually the primary rate plan like total.PG&E.E-TOU-D+PG&E.G-1)
            cost_value = df.loc[expected_scenario]
            if hasattr(cost_value, 'iloc'):
                return float(cost_value.iloc[0])
            else:
                return float(cost_value)
        else:
            log(
                at="load_annual_costs",
                info="scenario_not_found",
                expected_scenario=expected_scenario,
                file_path=file_path,
                available_scenarios=list(df.index)
            )
            return 0.0
            
    except Exception as e:
        log(
            at="load_annual_costs",
            info="annual_costs_load_failed",
            county=county,
            scenario=scenario,
            with_solar=with_solar,
            error=str(e)
        )
        return 0.0


def calculate_payback_periods(base_input_dir: str, scenario: str, housing_type: str, counties: list) -> pd.DataFrame:
    """
    Calculate payback periods for all counties and incentive scenarios.
    
    Args:
        base_input_dir: Base input directory
        scenario: Electrification scenario name  
        housing_type: Housing type
        counties: List of counties to process
        
    Returns:
        DataFrame with payback period data
    """
    try:
        # Load capital costs data from step15 (electrification appliances only)
        capital_costs_df = load_capital_costs(base_input_dir, scenario, housing_type)
        log(
            at="calculate_payback_periods",
            info="electrification_capital_costs_loaded",
            rows_count=len(capital_costs_df)
        )
        
        if capital_costs_df.empty:
            log(
                at="calculate_payback_periods",
                info="no_capital_costs_found",
                scenario=scenario
            )
            return pd.DataFrame()
        
        # Group capital costs by county and incentive scenario
        capital_summary = capital_costs_df.groupby(['county', 'incentive_scenario'])['net_cost'].sum().reset_index()
        log(
            at="calculate_payback_periods",
            info="capital_costs_summary_created",
            combinations_count=len(capital_summary)
        )
        
        
        payback_data = []
        
        for county in counties:
            try:
                # 1. Baseline costs (no electrification)
                baseline_annual_cost = load_annual_costs(base_input_dir, county, "baseline", housing_type, with_solar=False)
                
                # 2. Scenario costs (electrification only, no solar)
                scenario_annual_cost = load_annual_costs(base_input_dir, county, scenario, housing_type, with_solar=False)
                
                # 3. Scenario + solar costs (electrification + solar+storage)
                scenario_solar_annual_cost = load_annual_costs(base_input_dir, county, scenario, housing_type, with_solar=True)
                
                if baseline_annual_cost == 0:
                    log(
                        at="calculate_payback_periods",
                        info="missing_baseline_cost_data",
                        county=county
                    )
                    continue
                    
                if scenario_annual_cost == 0 or scenario_solar_annual_cost == 0:
                    log(
                        at="calculate_payback_periods",
                        info="missing_scenario_cost_data",
                        county=county
                    )
                    continue
                
                # Calculate annual savings (baseline - scenario)
                savings_scenario_only = baseline_annual_cost - scenario_annual_cost
                savings_with_solar = baseline_annual_cost - scenario_solar_annual_cost
                
                print(f"{county}:")
                print(f"  Baseline: ${baseline_annual_cost:.0f}")
                print(f"  {scenario} only: ${scenario_annual_cost:.0f} (savings: ${savings_scenario_only:.0f})")
                print(f"  {scenario} + solar: ${scenario_solar_annual_cost:.0f} (savings: ${savings_with_solar:.0f})")
                
                # Get capital costs for this county
                county_capital = capital_summary[capital_summary['county'].str.contains(county.replace(' County', ''), case=False, na=False)]
                
                if county_capital.empty:
                    print(f"Warning: No capital costs found for {county}")
                    continue
                
                county_slug = slugify_county_name(county)
                
                # Calculate payback for each incentive scenario
                for _, capital_row in county_capital.iterrows():
                    incentive_scenario = capital_row['incentive_scenario']
                    net_capital_cost = capital_row['net_cost']  # This now includes solar/storage if generated with --include-solar-storage
                    
                    # Determine which savings to use based on available data
                    # If solar savings are positive, use those; otherwise use scenario-only if positive
                    if savings_with_solar > 0:
                        annual_savings = savings_with_solar
                        savings_type = "with_solar"
                    elif savings_scenario_only > 0:
                        annual_savings = savings_scenario_only 
                        savings_type = "scenario_only"
                    else:
                        # No positive savings available - set a very small value for very long payback
                        annual_savings = 0.01
                        savings_type = "no_savings"
                        print(f"  Warning: No positive savings for {county} {incentive_scenario}")
                    
                    # Calculate payback period in years
                    payback_years = net_capital_cost / annual_savings if annual_savings > 0 else float('inf')
                    
                    print(f"    {incentive_scenario}: Capital ${net_capital_cost:.0f}, Savings ${annual_savings:.0f} ({savings_type}), Payback {payback_years:.1f} years")
                    
                    payback_data.append({
                        'county': county,
                        'county_slug': slugify_county_name(county),
                        'scenario': scenario,
                        'housing_type': housing_type,
                        'incentive_scenario': incentive_scenario,
                        'baseline_annual_cost': baseline_annual_cost,
                        'scenario_annual_cost': scenario_annual_cost,
                        'scenario_solar_annual_cost': scenario_solar_annual_cost,
                        'annual_savings_scenario_only': savings_scenario_only,
                        'annual_savings_with_solar': savings_with_solar,
                        'annual_savings_used': annual_savings,
                        'savings_type': savings_type,
                        'net_capital_cost': net_capital_cost,
                        'payback_period_years': payback_years
                    })
                    
            except Exception as e:
                print(f"Error processing {county}: {e}")
                continue
        
        return pd.DataFrame(payback_data)
        
    except Exception as e:
        print(f"Error calculating payback periods: {e}")
        log(
            at="step16_payback_periods",
            info="payback_calculation_failed",
            scenario=scenario,
            error=str(e)
        )
        return pd.DataFrame()

def process(base_input_dir: str, scenario: str, housing_type: str, counties: list):
    """
    Calculate payback periods for the specified electrification scenario and save to CSV.
    
    Args:
        base_input_dir: Base input directory
        scenario: Electrification scenario name
        housing_type: Housing type
        counties: List of counties to process
    """
    log(
        at="step16_payback_periods",
        info="starting_payback_calculations",
        scenario=scenario,
        housing_type=housing_type,
        counties_count=len(counties)
    )
    
    try:
        # Calculate payback periods
        payback_df = calculate_payback_periods(base_input_dir, scenario, housing_type, counties)
        
        if payback_df.empty:
            log(
                at="step16_payback_periods",
                info="no_payback_data_calculated",
                scenario=scenario
            )
            print(f"No payback data calculated for scenario: {scenario}")
            return
        
        # Save payback data to CSV
        output_dir = os.path.join("data", "results", housing_type)
        os.makedirs(output_dir, exist_ok=True)
        
        csv_path = os.path.join(output_dir, f"payback_periods_{scenario}.csv")
        payback_df.to_csv(csv_path, index=False)
        
        # Get summary stats
        valid_payback = payback_df[payback_df['payback_period_years'] != float('inf')]
        avg_payback = valid_payback['payback_period_years'].mean() if not valid_payback.empty else 0
        incentive_scenarios = payback_df['incentive_scenario'].unique()
        
        log(
            at="step16_payback_periods",
            info="payback_calculations_completed",
            scenario=scenario,
            csv_path=csv_path,
            counties_processed=len(payback_df['county'].unique()),
            incentive_scenarios=len(incentive_scenarios),
            average_payback_years=avg_payback
        )
        
        print(f"Payback period calculations completed for {scenario}")
        print(f"   CSV saved: {csv_path}")
        print(f"   Counties processed: {len(payback_df['county'].unique())}")
        print(f"   Incentive scenarios: {len(incentive_scenarios)}")
        print(f"   Average payback: {avg_payback:.1f} years")
        
        return csv_path
        
    except Exception as e:
        log(
            at="step16_payback_periods",
            info="payback_calculations_failed",
            scenario=scenario,
            error=str(e)
        )
        print(f"Failed to calculate payback periods for {scenario}: {e}")
        raise

if __name__ == "__main__":
    import argparse
    from scenarios import SCENARIOS
    
    parser = argparse.ArgumentParser(description="Calculate payback periods for electrification scenarios")
    parser.add_argument("scenario", 
                       choices=list(SCENARIOS.keys()),
                       help="Electrification scenario to analyze")
    parser.add_argument("--housing-type", default="single-family-detached",
                       help="Housing type (default: single-family-detached)")
    parser.add_argument("--counties", nargs="*", 
                       help="Counties to analyze (default: all counties)")
    
    args = parser.parse_args()
    
    # Use provided counties or default to all California counties
    if args.counties:
        counties = args.counties
    else:
        counties = norcal_counties + socal_counties + central_counties
    
    process(
        base_input_dir="data/loadprofiles",
        scenario=args.scenario,
        housing_type=args.housing_type,
        counties=counties
    )